// src/components/List/ListComponent.vue
<template lang="pug">
.container 
    .list-component__wrapper
        UserLists
        UserActiveList
</template>

<script>
import UserLists from "@/components/List/UserLists.vue"
import UserActiveList from "@/components/List/UserActiveList.vue"
export default {
    components: {
        UserLists,
        UserActiveList
    }
}
</script>

// src/components/List/ListComponent.jsx
import React from 'react'
import UserActiveList from './UserActiveList'
import UserLists from './UserLists'

function ListComponent() {
  return (
    <div className="container">
        <div className='list-component__wrapper'>
            <UserLists/>
            <UserActiveList/>
        </div>
    </div>
  )
}

export default ListComponent
