// src/components/List/UserLists.jsx
import React from 'react'
import listIcon from "../../assets/svg/solar_bill-list-linear.svg";
import plusIcon from "../../assets/svg/ic_round-plus.svg";
import listsIcon from "../../assets/svg/fluent-mdl2_task-list.svg";
import settings from "../../assets/svg/material-symbols_settings.svg";
import deleteIcon from "../../assets/svg/ic_baseline-delete.svg";

function UserLists() {
  return (
    <div  className='user-lists'>
      <div className="user-lists__header">
        <div className="user-lists__header-content">
          <div className="user-lists__header-icon">
              <img src={listIcon} alt="" />
          </div>
          <h2 className='user-lists__header-title'>Ваши списки</h2>
        </div>
        <button className="user-lists__header-btn">
          <div className="user-lists__header-icon">
            <img src={plusIcon} alt="" />
          </div>
          <div className="user-lists__header-btn__text">Dобавить список</div>
        </button>
      </div>
      <div className="user-lists__block">
        <div className="user-lists__block-item active">
          <div className="lists-item__inner">
            <div className="lists-item__icon">
              <img src={listsIcon} alt="" />
            </div>
            <h2 className="lists-item__title">Активный список</h2>
            <div className="lists-item__type">открытый</div>
            <div className="lists-item__options">
              <div className="lists-item__settings">
                <img src={settings} alt="" />
              </div>
              <div className="lists-item__delete">
                <img src={deleteIcon} alt="" />
              </div>
            </div>
          </div>
        </div>
        <div className="user-lists__block-item">
          <div className="lists-item__inner">
            <div className="lists-item__icon">
              <img src={listsIcon} alt="" />
            </div>
            <h2 className="lists-item__title">Обычный список</h2>
            <div className="lists-item__type">закрытый</div>
            <div className="lists-item__options">
              <div className="lists-item__settings">
                <img src={settings} alt="" />
              </div>
              <div className="lists-item__delete">
                <img src={deleteIcon} alt="" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default UserLists

// src/components/List/UserLists.vue
<template lang="pug">
.user-lists
    .user-lists__header
        .user-lists__header-content
            .user-lists__header-icon
                img(src="@/assets/svg/solar_bill-list-linear.svg")
        button.user-lists__header-btn
            .user-lists__header-icon
                img(src="@/assets/svg/ic_round-plus.svg")
    .user-lists__block 
        .user-lists__block-item.active
            .lists-item__inner
                .lists-item__icon
                    img(src="@/assets/svg/solar_bill-list-linear.svg")
                h2.lists-item__title Активный список
                .lists-item__type открытый
                .lists-item__options
                    .lists-item__settings
                        img(src="@/assets/svg/material-symbols_settings.svg")
                    .lists-item__delete
                        img(src="@/assets/svg/ic_baseline-delete.svg")
                    
        .user-lists__block-item
            .lists-item__inner
                .lists-item__icon
                    img(src="@/assets/svg/solar_bill-list-linear.svg")
                h2.lists-item__title Обычный список
                .lists-item__type закрытый 
                .lists-item__options
                    .lists-item__settings
                        img(src="@/assets/svg/material-symbols_settings.svg")
                    .lists-item__delete
                        img(src="@/assets/svg/ic_baseline-delete.svg")
                    

</template>

<script>
export default {

}
</script>
