// src/components/Mainpage/Banner.jsx
import React from 'react';

const Banner = (props) => {
    let bannerAlign = 'banner';
    if (props.rowRev) {
        bannerAlign += ' row-reverse';
    }
    return (
        <div className="bg">
            <div className="container">
                <section  className={bannerAlign}>
                    <div className="banner-left">
                        <h2 className="banner-title">{props.text}</h2>
                        <a href="/" className="banner-btn">{props.buttonText}</a>
                    </div>
                    <div className="banner-right">
                        <div className="banner-img"></div>
                    </div>
                </section>
            </div>
        </div>
    );
};

export default Banner;

// src/components/Mainpage/Banner.vue
<template lang="pug">
.bg
    .container 
        section.banner(:class="bannerClass")
            .banner-left
                h2.banner-title  {{banner.text}}
                a.banner-btn(href="/") {{banner.btnText}}
            .banner-right 
                .banner-img 
</template>

<script>
export default {
    props: {
        banner: {
            type: Object,
            required: true
        },
        bannerClass: {
            type: String,
            required: false,
        }
    }
}
</script>
