// src/components/Mainpage/Instruction.vue
<template lang="pug">
.container
    section.instruction
        h2.instruction-title Пошаговая и нструкция:
        .instruction-block
            .instruction-item(v-for="(instruction, i) in instructionList" :key="instruction.id")
                .instruction-item__title Шаг {{i+1}}: {{instruction.title}}
                .instruction-item__descr {{instruction.descr}}
</template>

<script>
export default {
    data(){
        return {
            instructionList : [
                {id:1,title:"Регистрация на сайте", descr:`Первым шагом будет регистрация на нашем сайте. Просто нажмите на кнопку "Регистрация" и следуйте инструкциям. Вам потребуется ввести свое имя и электронный адрес, а также создать пароль.`},
                {id:2,title:"Создание нового списка", descr:`После регистрации и входа в свой аккаунт перейдите в раздел "Мои списки". Здесь вы найдете кнопку "Создать новый список". Придумайте название для вашего списка и введите его в соответствующее поле.`},
                {id:3,title:"Добавление подарков в список", descr:`Теперь вы готовы добавить подарки в свой список. Воспользуйтесь функцией поиска на нашем сайте, чтобы найти подарки, которые вы хотели бы получить. Каждый подарок можно добавить в список нажатием кнопки "Добавить в список".`},
                {id:5,title:"Редактирование и управление", descr:`Вы можете редактировать свой список в любое время, добавляя новые подарки или удаляя те, что уже не нужны. Вы также можете добавить комментарии к каждому подарку, чтобы дать более подробную информацию о своих предпочтениях.`},
                {id:5,title:"Поделитесь своим списком", descr:`Наконец, когда ваш список будет готов, вы сможете поделиться им с друзьями и близкими. Просто нажмите на кнопку "Поделиться" и выберите удобный для вас способ (электронная почта, социальные сети и т.д.).`},
            ]
        }
    }

}
</script>

// src/components/Mainpage/Instruction.jsx
import React from 'react';

const Instruction = () => {
    const instructionList = [
        {id:1,title:"Регистрация на сайте", descr:`Первым шагом будет регистрация на нашем сайте. Просто нажмите на кнопку "Регистрация" и следуйте инструкциям. Вам потребуется ввести свое имя и электронный адрес, а также создать пароль.`},
        {id:2,title:"Создание нового списка", descr:`После регистрации и входа в свой аккаунт перейдите в раздел "Мои списки". Здесь вы найдете кнопку "Создать новый список". Придумайте название для вашего списка и введите его в соответствующее поле.`},
        {id:3,title:"Добавление подарков в список", descr:`Теперь вы готовы добавить подарки в свой список. Воспользуйтесь функцией поиска на нашем сайте, чтобы найти подарки, которые вы хотели бы получить. Каждый подарок можно добавить в список нажатием кнопки "Добавить в список".`},
        {id:5,title:"Редактирование и управление", descr:`Вы можете редактировать свой список в любое время, добавляя новые подарки или удаляя те, что уже не нужны. Вы также можете добавить комментарии к каждому подарку, чтобы дать более подробную информацию о своих предпочтениях.`},
        {id:5,title:"Поделитесь своим списком", descr:`Наконец, когда ваш список будет готов, вы сможете поделиться им с друзьями и близкими. Просто нажмите на кнопку "Поделиться" и выберите удобный для вас способ (электронная почта, социальные сети и т.д.).`},
    ]
    return (
        <div className="container">
            <section className='instruction'>
                <h2 className="instruction-title">Пошаговая и нструкция:</h2>
                <div className="instruction-block">
                    {instructionList.map((item,i) => (
                        <div className="instruction-item" key={item.id}>
                            <div className="instruction-item__title">Шаг {i+1}: {item.title}</div>
                            <div className="instruction-item__descr">{item.descr}</div>
                        </div>
                    ))}
                </div>
            </section>
        </div>
    );
};

export default Instruction;
