// src/components/Footer.jsx
import React from 'react';
import logo from '../assets/images/logo.png';

const Footer = () => {
    const footerMenu = [
        {   
            name: "Поддержка",
            secondLevel:[{id:1,title:"Помощь", link:"#"},{id:2,title:"Связаться с нами", link:"#"},{id:3,title:"Отзывы", link:"#"},{id:4,title:"Обратная связь", link:"#"}]
        },
        {
            name: "О нас",
            secondLevel:[{id:1,title:"История", link:"#"},{id:2,title:"Наша цель", link:"#"},{id:3,title:"Новости", link:"#"},{id:4,title:"Партнеры", link:"#"}]
        },
        {
            name: "Мы тут",
            secondLevel: [{id:1,icon: ""},{id:2,icon: ""},{id:3,icon: ""}]
        },
    ];
    const mobileFooterMenu = [
        {
            name: "Мы тут",
            secondLevel: [{id:1,icon: ""},{id:2,icon: ""},{id:3,icon: ""}]
        },
        {
            name: "О нас",
            secondLevel:[{id:1,title:"История", link:"#"},{id:2,title:"Наша цель", link:"#"},{id:3,title:"Новости", link:"#"},{id:4,title:"Партнеры", link:"#"}]
        },
        {   
            name: "Поддержка",
            secondLevel:[{id:1,title:"Помощь", link:"#"},{id:2,title:"Связаться с нами", link:"#"},{id:3,title:"Отзывы", link:"#"},{id:4,title:"Обратная связь", link:"#"}]
        },
    ]
    return (
        <footer className='footer'>
            <div className="footer-block">
                <div className="container">
                    <div className="footer-up">
                        <div className="footer-up__block">
                            <div className="footer-up__left">
                                <div className="footer-logo__wrapper">
                                    <div className="footer-logo">
                                        <a href=""><img src={logo} alt="" className="logo" /></a>
                                    </div>
                                </div>
                            </div>
                            <div className="footer-up__right">
                                {
                                    footerMenu.map((menu, l) => (
                                        <div className="footer-menu__wrapper" key={l}>
                                            <h2 className="footer-menu__title">{menu.name}</h2>                                         
                                            <ul className="footer-menu">
                                                {
                                                    menu.secondLevel.map(secondLevelItem => (
                                                        <li key={secondLevelItem.id} className='footer-menu__li'>
                                                            {secondLevelItem.title && <a href={secondLevelItem.link} className='footer-menu__link'>{secondLevelItem.title}</a>}
                                                            {secondLevelItem.icon && <i className={secondLevelItem.icon}></i>}
                                                        </li>
                                                    ))
                                                }
                                            </ul>
                                        </div>
                                    ))
                                }
                            </div>
                        </div>
                        <div className="footer-up__block isMobile">
                            <div className="footer-logo__wrapper">
                                <div className="footer-logo">
                                        <a href=""><img src={logo} alt="" className="logo" /></a>
                                </div>
                            </div>
                            {
                                    mobileFooterMenu.map((menu, l) => (
                                        <div className="footer-menu__wrapper" key={l}>
                                            <h2 className="footer-menu__title">{menu.name}</h2>                                         
                                            <ul className="footer-menu">
                                                {
                                                    menu.secondLevel.map(secondLevelItem => (
                                                        <li key={secondLevelItem.id} className='footer-menu__li'>
                                                            {secondLevelItem.title && <a href={secondLevelItem.link} className='footer-menu__link'>{secondLevelItem.title}</a>}
                                                            {secondLevelItem.icon && <i className={secondLevelItem.icon}></i>}
                                                        </li>
                                                    ))
                                                }
                                            </ul>
                                        </div>
                                    ))
                                }
                        </div>
                    </div>
                </div>
                <div className="footer-bottom">
                    <div className="container">
                        <div className="footer-bottom__block">
                            <div className="footer-bottom__item">
                                <div className="footer-bottom__text">2023 Mywish All Rights Reserved.</div>
                            </div>
                            <div className="footer-bottom__item">
                                <p className="footer-bottom__text">Политика конфиденциальности</p>
                                <p className="footer-bottom__text">Условия эксплуатации</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="footer-bg"></div>
        </footer>
    );
};

export default Footer;

// src/components/Footer.vue
<template lang="pug">
footer.footer
    .footer-block
        .container
            .footer-up
                .footer-up__block
                    .footer-up__left
                        .footer-logo__wrapper
                            .footer-logo
                                a(href="")
                                    img(src="@/assets/images/logo.png", alt="alt")
                    .footer-up__right
                        .footer-menu__wrapper(v-for="menu in footerMenu" :key="menu.id")
                            h2.footer-menu__title {{menu.name}}
                            ul.footer-menu
                                li.footer-menu__li(v-for="secondLevel in menu.secondLevel" :key="secondLevel.id")
                                    a(:href="secondLevel.link" v-if="secondLevel.title") {{secondLevel.title}}
                                    i(v-if="secondLevel.icon" :class="secondLevel.icon")
                .footer-up__block.isMobile
                    .footer-logo__wrapper
                        .footer-logo
                            a(href="")
                                img.logo(src="@/assets/images/logo.png")
                    .footer-menu__wrapper(v-for="menu in footerMenu" :key="menu.id")
                        h2.footer-menu__title {{menu.name}}
                        ul.footer-menu
                            li(v-for="secondLevel in menu.secondLevel" :key="secondLevel.id")
                                a(v-if="secondLevel.title" :href="secondLevel.link") {{secondLevel.title}}
                                i(v-if="secondLevel.icon" :class="secondLevel.icon")
        .footer-bottom
            .container
                .footer-bottom__block
                    .footer-bottom__item
                        .footer-bottom__text  2023 Mywish All Rights Reserved.
                    .footer-bottom__item
                        p.footer-bottom__text  Политика конфиденциальности
                        p.footer-bottom__text  Условия эксплуатации
    .footer-bg
</template>

<script>
export default {
  data() {
    return {
      footerMenu: [
        {
          name: 'Поддержка',
          secondLevel: [
            { id: 1, title: 'Помощь', link: '#' },
            { id: 2, title: 'Связаться с нами', link: '#' },
            { id: 3, title: 'Отзывы', link: '#' },
            { id: 4, title: 'Обратная связь', link: '#' },
          ],
        },
        {
          name: 'О нас',
          secondLevel: [
            { id: 1, title: 'История', link: '#' },
            { id: 2, title: 'Наша цель', link: '#' },
            { id: 3, title: 'Новости', link: '#' },
            { id: 4, title: 'Партнеры', link: '#' },
          ],
        },
        {
          name: 'Мы тут',
          secondLevel: [
            { id: 1, icon: '' },
            { id: 2, icon: '' },
            { id: 3, icon: '' },
          ],
        },
      ],
      mobileFooterMenu: [
        {
          name: 'Мы тут',
          secondLevel: [
            { id: 1, icon: '' },
            { id: 2, icon: '' },
            { id: 3, icon: '' },
          ],
        },
        {
          name: 'О нас',
          secondLevel: [
            { id: 1, title: 'История', link: '#' },
            { id: 2, title: 'Наша цель', link: '#' },
            { id: 3, title: 'Новости', link: '#' },
            { id: 4, title: 'Партнеры', link: '#' },
          ],
        },
        {
          name: 'Поддержка',
          secondLevel: [
            { id: 1, title: 'Помощь', link: '#' },
            { id: 2, title: 'Связаться с нами', link: '#' },
            { id: 3, title: 'Отзывы', link: '#' },
            { id: 4, title: 'Обратная связь', link: '#' },
          ],
        },
      ],
    }
  },
}
</script>
